# frozen_string_literal: true

require 'evil/client'
require 'tempfile'

require 'true-conf/client'
require 'true-conf/conference'
require 'true-conf/invitation'
require 'true-conf/participant'
require 'true-conf/record'
require 'true-conf/user'
require 'true-conf/version'
require 'true-conf/response'
require 'true-conf/callable'
require 'true-conf/optional'
require 'true-conf/error'
require 'true-conf/error_detail'
require 'true-conf/entity/conference'
require 'true-conf/entity/conference_simple'
require 'true-conf/entity/participant'
require 'true-conf/entity/user'
require 'true-conf/entity/user_simple'
require 'true-conf/entity/user_list'
require 'true-conf/entity/invitation'
require 'true-conf/entity/invitation_simple'
require 'true-conf/entity/invitation_list'
require 'true-conf/entity/record'
require 'true-conf/entity/record_list'
